apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-store
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: key-value-store
  template:
    metadata:
      labels:
        app: key-value-store
    spec:
      containers:
      - image: ghcr.io/osobky/key-value-store:latest
        name: key-value-store
        ports:
        - containerPort: 8000